### ISSUE TITLE
new recipes for grinder_recipes.lua

### ISSUE THREAD

**Issue by Irremann** [minestead/minestead_mods#26]
if minetest.get_modpath("caverealms") then
	table.insert(recipes, {"caverealms:salt_crystal", "farming:salt 4"})
	table.insert(recipes, {"caverealms:stone_with_salt", "farming:salt 2"})
	table.insert(recipes, {"caverealms:salt_gem", "farming:salt 1"})
	table.insert(recipes, {"caverealms:glow_mese", "default:mese_crystal_fragment 5"})
end

**Comment by technix** [comment]
fixed
